Library Imports: Loads core libraries for data manipulation and math operations.

In [105]:
import numpy as np
import pandas as pd

Data Loading: Loads the student dataset into a Pandas DataFrame.

In [106]:
df=pd.read_csv("academic_survival & students dropout risks.csv")

Data Preview: Displays the first 5 rows of the dataset to inspect structure and sample values.

In [107]:
df.head()

,Student_ID,Age,Gender,First_Generation,Family_Income,Household_Size,Housing_Status,Scholarship,Tuition_Base,Semester,...,Emergency_Expense,Sem_GPA,Attendance,LMS_Logins,Advising_Visits,Failed_Courses,Financial_Stress,Target_Dropout_Next_Sem,End_of_Semester_Status,Censored
0,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,1,...,0.0,2.85,85.8,67.0,0,0,1.7,0,Enrolled,0
1,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,2,...,0.0,2.73,81.0,89.0,1,0,3.1,0,Enrolled,0
2,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,3,...,0.0,2.60,78.3,60.0,0,2,3.0,0,Enrolled,0
3,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,4,...,0.0,2.34,77.2,59.0,2,3,5.1,0,Enrolled,0
4,STU_00001,18,Female,0,15000.0,2,Off-Campus,0,15000,5,...,0.0,1.90,79.3,53.0,1,2,3.6,0,Enrolled,1

Data Summary: Checks total rows, column data types, and missing values count.

In [108]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79239 entries, 0 to 79238
Data columns (total 22 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Student_ID               79239 non-null  object
 1   Age                      79239 non-null  int64
 2   Gender                   79239 non-null  object
 3   First_Generation         79239 non-null  int64
 4   Family_Income            75635 non-null  float64
 5   Household_Size           79239 non-null  int64
 6   Housing_Status           79239 non-null  object
 7   Scholarship              79239 non-null  int64
 8   Tuition_Base             79239 non-null  int64
 9   Semester                 79239 non-null  int64
 10  Course_Load              79239 non-null  int64
 11  Work_Hours               79239 non-null  float64
 12  Emergency_Expense        79239 non-null  float64
 13  Sem_GPA                  79239 non-null  float64
 14  Attendance               79239 non-null  float64
 15  LMS_Logins               78372 non-null  float64
 16  Advising_Visits          79239 non-null  int64
 17  Failed_Courses           79239 non-null  int64
 18  Financial_Stress         79239 non-null  float64
 19  Target_Dropout_Next_Sem  79239 non-null  int64
 20  End_of_Semester_Status   79239 non-null  object
 21  Censored                 79239 non-null  int64
dtypes: float64(7), int64(11), object(4)
memory usage: 13.3+ MB

Feature Selection: Drops IDs and leakage columns (Student_ID, Censored, End_of_Semester_Status).

In [109]:

df_clean = df.drop(columns=["Student_ID", "Censored"], errors="ignore")
df_clean = df_clean.drop(columns=["End_of_Semester_Status"], errors="ignore")

Data Verification: Previews the first 5 rows to confirm columns are removed.

In [110]:
df_clean.head()

,Age,Gender,First_Generation,Family_Income,Household_Size,Housing_Status,Scholarship,Tuition_Base,Semester,Course_Load,Work_Hours,Emergency_Expense,Sem_GPA,Attendance,LMS_Logins,Advising_Visits,Failed_Courses,Financial_Stress,Target_Dropout_Next_Sem
0,18,Female,0,15000.0,2,Off-Campus,0,15000,1,15,18.4,0.0,2.85,85.8,67.0,0,0,1.7,0
1,18,Female,0,15000.0,2,Off-Campus,0,15000,2,15,23.1,0.0,2.73,81.0,89.0,1,0,3.1,0
2,18,Female,0,15000.0,2,Off-Campus,0,15000,3,15,19.1,0.0,2.60,78.3,60.0,0,2,3.0,0
3,18,Female,0,15000.0,2,Off-Campus,0,15000,4,15,26.5,0.0,2.34,77.2,59.0,2,3,5.1,0
4,18,Female,0,15000.0,2,Off-Campus,0,15000,5,18,25.4,0.0,1.90,79.3,53.0,1,2,3.6,0

Missing Imputation: Fills missing values in Family_Income using the median.

In [111]:
df_clean["Family_Income"].fillna( df_clean["Family_Income"].median(), inplace=True)
df_clean["LMS_Logins"].fillna(df_clean["LMS_Logins"].median(), inplace=True)

C:\Users\khany\AppData\Local\Temp\ipykernel_24868\4222758245.py:1: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean["Family_Income"].fillna( df_clean["Family_Income"].median(), inplace=True)
C:\Users\khany\AppData\Local\Temp\ipykernel_24868\4222758245.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df_clean["LMS_Logins"].fillna(df_clean["LMS_Logins"].median(), inplace=True)

Null Verification: Confirms zero missing values remain in the entire dataset.

In [112]:
print("Null values remaining:", df_clean.isnull().sum().sum())

Null values remaining: 0

Data Check: Verifies total columns (19) and non-null counts after cleaning.

In [113]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 79239 entries, 0 to 79238
Data columns (total 19 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   Age                      79239 non-null  int64
 1   Gender                   79239 non-null  object
 2   First_Generation         79239 non-null  int64
 3   Family_Income            79239 non-null  float64
 4   Household_Size           79239 non-null  int64
 5   Housing_Status           79239 non-null  object
 6   Scholarship              79239 non-null  int64
 7   Tuition_Base             79239 non-null  int64
 8   Semester                 79239 non-null  int64
 9   Course_Load              79239 non-null  int64
 10  Work_Hours               79239 non-null  float64
 11  Emergency_Expense        79239 non-null  float64
 12  Sem_GPA                  79239 non-null  float64
 13  Attendance               79239 non-null  float64
 14  LMS_Logins               79239 non-null  float64
 15  Advising_Visits          79239 non-null  int64
 16  Failed_Courses           79239 non-null  int64
 17  Financial_Stress         79239 non-null  float64
 18  Target_Dropout_Next_Sem  79239 non-null  int64
dtypes: float64(7), int64(10), object(2)
memory usage: 11.5+ MB

Categorical Encoding: Converts text columns (object types) into numeric numbers using LabelEncoder.

In [114]:
from sklearn.preprocessing import LabelEncoder

label_encoders = {}
categorical_cols = df_clean.select_dtypes(include=["object"]).columns

for col in categorical_cols:
    le = LabelEncoder()
    df_clean[col] = le.fit_transform(df_clean[col].astype(str))
    label_encoders[col] = le

Data Splitting: Separates predictors (X) from the main target variable (y: Target_Dropout_Next_Sem).

In [115]:
X = df_clean.drop(columns=["Target_Dropout_Next_Sem"])
y = df_clean["Target_Dropout_Next_Sem"]

Dimension Check: Prints the shapes of X (79239, 18) and y to verify feature count.

In [116]:
print("Features (X) Shape:", X.shape)
print("Target (y) Shape:", y.shape)

Features (X) Shape: (79239, 18)
Target (y) Shape: (79239,)

Train-Test Split: Splits data into 80% train and 20% test sets.

In [117]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

print("X_train Shape:", X_train.shape)
print("X_test Shape:", X_test.shape)

X_train Shape: (63391, 18)
X_test Shape: (15848, 18)

ML Imports: Loads Random Forest, Scaler, Metrics, and Joblib.

In [118]:
import joblib
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# 1. Train-Test Split (80% Train, 20% Test)
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42, stratify=y
)

# 2. Feature Scaling
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

# 3. Model Training
model = RandomForestClassifier(n_estimators=100, random_state=42)
model.fit(X_train_scaled, y_train)

# 4. Evaluation
y_pred = model.predict(X_test_scaled)
print("--- Model Evaluation ---")
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

# 5. Save Model and Scaler
joblib.dump(model, "dropout_model.pkl")
joblib.dump(scaler, "scaler.pkl")
print("\nModel and Scaler Saved Successfully!")

C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
Traceback (most recent call last):
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\gradio\queueing.py", line 759, in process_events
    response = await route_utils.call_process_api(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<5 lines>...
    )
    ^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\gradio\route_utils.py", line 354, in call_process_api
    output = await app.get_blocks().process_api(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<11 lines>...
    )
    ^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\gradio\blocks.py", line 2191, in process_api
    result = await self.call_function(
             ^^^^^^^^^^^^^^^^^^^^^^^^^
    ...<8 lines>...
    )
    ^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\gradio\blocks.py", line 1698, in call_function
    prediction = await anyio.to_thread.run_sync(  # type: ignore
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        fn, *processed_input, limiter=self.limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\anyio\to_thread.py", line 65, in run_sync
    return await get_async_backend().run_sync_in_worker_thread(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        func, args, abandon_on_cancel=abandon_on_cancel, limiter=limiter
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\anyio\_backends\_asyncio.py", line 2706, in run_sync_in_worker_thread
    return await future
           ^^^^^^^^^^^^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\anyio\_backends\_asyncio.py", line 1100, in run
    result = context.run(func, *args)
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\gradio\utils.py", line 915, in wrapper
    response = f(*args, **kwargs)
  File "C:\Users\khany\AppData\Local\Temp\ipykernel_24868\2103850256.py", line 20, in predict_dropout
    prediction = model.predict(input_scaled)[0]
                 ~~~~~~~~~~~~~^^^^^^^^^^^^^^
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\ensemble\_forest.py", line 903, in predict
    proba = self.predict_proba(X)
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\ensemble\_forest.py", line 945, in predict_proba
    X = self._validate_X_predict(X)
  File "C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\ensemble\_forest.py", line 610, in _validate_X_predict
    if self.estimators_[0]._support_missing_values(X):
       ~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

--- Model Evaluation ---
Accuracy: 0.916140837960626

Classification Report:
               precision    recall  f1-score   support

           0       0.92      0.99      0.96     14465
           1       0.63      0.10      0.17      1383

    accuracy                           0.92     15848
   macro avg       0.77      0.55      0.56     15848
weighted avg       0.89      0.92      0.89     15848


Model and Scaler Saved Successfully!

Installation: Installs Gradio library for UI deployment.

In [119]:
!pip install gradio

C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages\sklearn\utils\validation.py:2827: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: gradio in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (5.50.0)
Requirement already satisfied: aiofiles<25.0,>=22.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (24.1.0)
Requirement already satisfied: anyio<5.0,>=3.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (4.15.1)
Requirement already satisfied: audioop-lts<1.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.2.2)
Requirement already satisfied: brotli>=1.1.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (1.2.0)
Requirement already satisfied: fastapi<1.0,>=0.115.2 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.142.2)
Requirement already satisfied: ffmpy in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (1.0.0)
Requirement already satisfied: gradio-client==1.14.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (1.14.0)
Requirement already satisfied: groovy~=0.1 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.1.2)
Requirement already satisfied: httpx<1.0,>=0.24.1 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.28.1)
Requirement already satisfied: huggingface-hub<2.0,>=0.33.5 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (1.33.0)
Requirement already satisfied: jinja2<4.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (3.1.6)
Requirement already satisfied: markupsafe<4.0,>=2.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (3.0.4)
Requirement already satisfied: numpy<3.0,>=1.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (2.4.6)
Requirement already satisfied: orjson~=3.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (3.12.0)
Requirement already satisfied: packaging in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (26.2)
Requirement already satisfied: pandas<3.0,>=1.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (2.3.3)
Requirement already satisfied: pillow<12.0,>=8.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (11.3.0)
Requirement already satisfied: pydantic<=2.12.3,>=2.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (2.12.3)
Requirement already satisfied: pydub in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.25.1)
Requirement already satisfied: python-multipart>=0.0.18 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.0.32)
Requirement already satisfied: pyyaml<7.0,>=5.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (6.0.3)
Requirement already satisfied: ruff>=0.9.3 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.16.10)
Requirement already satisfied: safehttpx<0.2.0,>=0.1.6 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.1.7)
Requirement already satisfied: semantic-version~=2.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (2.10.0)
Requirement already satisfied: starlette<1.0,>=0.40.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.52.1)
Requirement already satisfied: tomlkit<0.14.0,>=0.12.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.13.3)
Requirement already satisfied: typer<1.0,>=0.12 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.27.2)
Requirement already satisfied: typing-extensions~=4.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (4.16.0)
Requirement already satisfied: uvicorn>=0.14.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio) (0.54.0)
Requirement already satisfied: fsspec in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio-client==1.14.0->gradio) (2026.9.0)
Requirement already satisfied: websockets<16.0,>=13.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from gradio-client==1.14.0->gradio) (15.0.1)
Requirement already satisfied: idna>=2.8 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from anyio<5.0,>=3.0->gradio) (3.20)
Requirement already satisfied: typing-inspection>=0.4.2 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.4.4)
Requirement already satisfied: annotated-doc>=0.0.2 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fastapi<1.0,>=0.115.2->gradio) (0.0.5)
Requirement already satisfied: opentelemetry-api>=1.44.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from fastapi<1.0,>=0.115.2->gradio) (1.45.0)
Requirement already satisfied: certifi in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (2026.7.22)
Requirement already satisfied: httpcore==1.* in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpx<1.0,>=0.24.1->gradio) (1.0.9)
Requirement already satisfied: h11>=0.16 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from httpcore==1.*->httpx<1.0,>=0.24.1->gradio) (0.16.0)
Requirement already satisfied: click<9.0.0,>=8.4.2 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (8.5.0)
Requirement already satisfied: filelock>=3.10.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.6.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (1.6.0)
Requirement already satisfied: tqdm>=4.42.1 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from huggingface-hub<2.0,>=0.33.5->gradio) (4.70.1)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas<3.0,>=1.0->gradio) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas<3.0,>=1.0->gradio) (2026.5)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pandas<3.0,>=1.0->gradio) (2026.2)
Requirement already satisfied: annotated-types>=0.6.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<=2.12.3,>=2.0->gradio) (0.8.0)
Requirement already satisfied: pydantic-core==2.41.4 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from pydantic<=2.12.3,>=2.0->gradio) (2.41.4)
Requirement already satisfied: shellingham>=1.3.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from typer<1.0,>=0.12->gradio) (1.5.4)
Requirement already satisfied: rich>=13.8.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from typer<1.0,>=0.12->gradio) (15.0.0)
Requirement already satisfied: colorama in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from typer<1.0,>=0.12->gradio) (0.4.6)
Requirement already satisfied: six>=1.5 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from python-dateutil>=2.8.2->pandas<3.0,>=1.0->gradio) (1.17.0)
Requirement already satisfied: markdown-it-py>=2.2.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (4.2.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from rich>=13.8.0->typer<1.0,>=0.12->gradio) (2.20.0)
Requirement already satisfied: mdurl~=0.1 in C:\Users\khany\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\LocalCache\local-packages\Python313\site-packages (from markdown-it-py>=2.2.0->rich>=13.8.0->typer<1.0,>=0.12->gradio) (0.1.2)

[notice] A new release of pip is available: 26.1.2 -> 26.2.1
[notice] To update, run: C:\Users\khany\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.13_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip

Gradio Setup: Loads saved .pkl files and defines prediction function.

In [ ]:
import gradio as gr
import joblib
import numpy as np
import pandas as pd

# 1. Saved Model & Scaler
model = joblib.load("dropout_model.pkl")
scaler = joblib.load("scaler.pkl")


# 2. Prediction Function
def predict_dropout(*args):
    
    input_data = np.array(args).reshape(1, -1)

    # Scaling
    input_scaled = scaler.transform(input_data)

    # Prediction
    prediction = model.predict(input_scaled)[0]
    probability = model.predict_proba(input_scaled)[0][1]

    if prediction == 1:
        return f"⚠️ High Risk of Dropout (Probability: {probability:.2%})"
    else:
        return f"✅ Low Risk / Student Likely to Continue (Probability: {1 - probability:.2%})"



feature_names = list(X.columns)
input_components = []

for col in feature_names:
    input_components.append(gr.Number(label=col, value=0))

# 4. Gradio Interface
interface = gr.Interface(
    fn=predict_dropout,
    inputs=input_components,
    outputs=gr.Textbox(label="Prediction Result"),
    title="Academic Survival & Student Dropout Risk Predictor",
    description="Enter student features to predict the dropout risk for the next semester.",
)

# Launch App
interface.launch(share=True)

* Running on local URL:  http://127.0.0.1:7866